"""buat tabel siswa

Revision ID: 407a96e9ea93
Revises: 825b7e82ad62
Create Date: 2022-01-26 09:25:24.271447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407a96e9ea93'
down_revision = '825b7e82ad62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siswa',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('no_urut', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('kelas', sa.String(length=10), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('id_guru', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_guru'], ['guru.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa')
    # ### end Alembic commands ###
