"""buat tabel guru

Revision ID: 825b7e82ad62
Revises: 744f6b65ca7a
Create Date: 2022-01-26 08:44:19.630441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825b7e82ad62'
down_revision = '744f6b65ca7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guru',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nip', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guru')
    # ### end Alembic commands ###
